# Generated by Django 5.2.7 on 2025-11-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_phone_active',
            field=models.BooleanField(default=False),
        ),
    ]
