# Generated by Django 5.2.7 on 2025-11-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customuser_is_email_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default=None, upload_to='uploads/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default=None, upload_to='uploads/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default=None, upload_to='uploads/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default=None, upload_to='uploads/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(default=None, upload_to='uploads/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image6',
            field=models.ImageField(default=None, upload_to='uploads/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image7',
            field=models.ImageField(default=None, upload_to='uploads/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image8',
            field=models.ImageField(default=None, upload_to='uploads/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image9',
            field=models.ImageField(default=None, upload_to='uploads/product/'),
            preserve_default=False,
        ),
    ]
