# Generated by Django 5.2.7 on 2025-11-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_phonelotp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhonelOTP',
            new_name='PhoneOTP',
        ),
    ]
