# Generated by Django 5.2.7 on 2025-11-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_rename_phonelotp_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
