# Generated by Django 5.2.7 on 2025-11-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='is_used',
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='code',
            field=models.IntegerField(),
        ),
    ]
