# Generated by Django 5.2.7 on 2025-11-29 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
