# Generated by Django 5.2.7 on 2025-11-29 03:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_rename_address_customuser_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z\\- ]+$', 'Enter a valid postal code')]),
        ),
    ]
