# Generated by Django 5.2.7 on 2025-12-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_customuser_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
