# Generated by Django 5.2.7 on 2025-12-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_address_nickname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
