# Generated by Django 5.2.7 on 2025-12-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='newsletter_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
