# Generated by Django 5.2.7 on 2025-12-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
