# Generated by Django 5.2.7 on 2025-12-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_remove_comment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added']},
        ),
    ]
