# Generated by Django 5.2.7 on 2025-12-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0041_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("verification", "Email Verification"),
                    ("password_reset", "Password Reset"),
                ],
                default="verification",
                max_length=20,
            ),
        ),
    ]
