# Generated by Django 5.2.7 on 2025-12-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vnpay_transaction_no',
            new_name='payment_transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('vnpay', 'VNPay'), ('paypal', 'PayPal')], max_length=20, null=True),
        ),
    ]
